version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"       
      - "9001:9001"        
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cloud_storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_storage_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio

  letton_cloud_backend:
    image: dolbonya/letton_cloud_backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./letton_cloud_backend./.env
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres-data:
  minio-data: